language: python
branches:
  only:
    - master
sudo: false
python:
  - 3.7
before_script:
  - pip install -U pip
  - pip install sphinx
  - pip install sphinx-rtd-theme
script:
  - make html
  - touch ./build/html/.nojekyll
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./build/html
  keep-history: false
  on:
    branch: master
