name: GH-Pages
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install sphinx
          python -m pip install sphinx-rtd-theme

      - name: Build
        run: |
          make html
          touch ./build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: ./build/html
          git-config-name: Nicola Coretti
          git-config-email: nico.coretti@gmail.com